ENV['APP_IDENTIFIER'] = 'com.moonlight.composeplayground'
ENV['APP_NAME'] = 'composeplayground'
ENV['APP_SCHEME'] = 'composeplayground'

ENV['BADGE_DARK'] = 'true'

import_from_git(url: 'git@github.com:futuredapp/fastlane.git')
